/*
 * pe.validator.doi
 * COPYLEFT 2025
 * Ingenieria Informatica Yupay SACS
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 *  with this program. If not, see <https://www.gnu.org/licenses/>.
 */

-- Oracle package holding canonical DOI constants
CREATE OR REPLACE PACKAGE doi_constants AS
    OTHERS       CONSTANT VARCHAR2(16) := 'OTHERS';
DNI          CONSTANT VARCHAR2(16) := 'DNI';
PNP          CONSTANT VARCHAR2(16) := 'PNP';
CE           CONSTANT VARCHAR2(16) := 'CE';
RUC          CONSTANT VARCHAR2(16) := 'RUC';
PASSPORT     CONSTANT VARCHAR2(16) := 'PASSPORT';
REFUGEE      CONSTANT VARCHAR2(16) := 'REFUGEE';
DIPLOMATIC   CONSTANT VARCHAR2(16) := 'DIPLOMATIC';
PTP          CONSTANT VARCHAR2(16) := 'PTP';
ID           CONSTANT VARCHAR2(16) := 'ID';
ID_PTP       CONSTANT VARCHAR2(16) := 'ID_PTP';
TIN          CONSTANT VARCHAR2(16) := 'TIN';
END doi_constants;
/

-- Table with CHECK constraint
CREATE TABLE person (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        name VARCHAR2(200) NOT NULL,
                        doi_type VARCHAR2(16) NOT NULL,
                        doi_number VARCHAR2(32) NOT NULL,
                        CONSTRAINT chk_doi_type CHECK (doi_type IN (
                                                                    'OTHERS','DNI','PNP','CE','RUC','PASSPORT',
                                                                    'REFUGEE','DIPLOMATIC','PTP','ID','ID_PTP','TIN'
                            ))
);
